name: user_repository
description: new flutter project
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true