name: fbbloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  easy_localization: ^3.0.4
  flutter_screenutil: ^5.9.0
  like_button: ^2.0.5
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  animated_splash_screen: ^1.3.0
  dio: ^5.4.2
  retrofit: ^4.1.0
  firebase_messaging: ^14.8.1
  flutter_local_notifications: ^17.0.0
  firebase_database: ^10.5.1
  firebase_core: ^2.29.0
  qr_code_scanner: ^1.0.1

 



  user_repository:
    path: packages/user_repository/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0 

  

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/translations/
  - assets/images/myphoto.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  fonts:
  - family: Great Vibes
    fonts:
     - asset: assets/fontlogo/GreatVibes-Regular.ttf
  


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true 
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true 



 
